---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nagios-install-server
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    #  - destroy
    #  - create
      - converge
    # - idempotence
    #  - lint
    #  - verify
    #  - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
